### ISSUE TITLE
[custom files processing] make the translation step optional

### ISSUE THREAD

**Issue by oolonek** [lotusnprod/lotus-processor#37]
When processing a custom input as described in https://github.com/lotusnprod/lotus-processor/wiki/Processing-your-own-referenced-structure-organism-pairs the workflow doesn't complete because no file is present in 'data/interim/tables_custom/1_translated/organism'. See here https://github.com/lotusnprod/lotus-processor/runs/8177716447?check_suite_focus=true#step:9:875

I guess this is because the kotlin translater has nothing to process. 
Indeed, when adding an organism to translate (e.g. Rose apple) as in the new [custom_example.tsv](https://github.com/lotusnprod/lotus-processor/blob/main/data/example/custom_example.tsv) the `make MODE=custom lotus-bloom`recipee works. 

I added these modification to the kotlin script https://github.com/lotusnprod/lotus-processor/commit/739412dc8d33b080d9be1296e6cc4f1f0a7591c7 so that a dummy tsv file containing the organism header and a  value (Rose apple) would be outputed whatever the result of the translation step would be. However it doesn't work.

Maybe adding a security (if file present proceed, else skip to next step) in this region would be a way to go https://github.com/lotusnprod/lotus-processor/blob/main/src/2_curating/2_editing/organism/3_processingTranslated.R#L165

@Adafede you should have a clearer view of the possible way to implement this here I guess.

**Comment by oolonek** [comment]
renaming the output as 01000.tsv and having a correct value for gnverifier (Syzygium jambos) 
See https://github.com/lotusnprod/lotus-processor/commit/12e8ee7f607fe3bd2197228ff1a4ee7852f286f7
However this is not OK since the writing of the 01000.tsv would overwrite possible correct translation of the script ... it should be made optional.

**Comment by Adafede** [comment]
@oolonek 02b976c2a76872e9df214bfb71c90dd7ad1ad4db Should be fixed

**Comment by oolonek** [comment]
👍
