### ISSUE TITLE
[manual mode] check input for MODE=manual command

### ISSUE THREAD

**Issue by oolonek** [lotusnprod/lotus-processor#4]
(Testing manual mode)

If I run 

`conda run -n lotus_env Rscript 1_gathering/db/manual/standardizing.R ../data/example/my_manual_example.tsv`

(using a modified manual_example.tsv file)

and then 
`conda run -n lotus_env MODE=manual make manual-entry`

The platinum.tsv.gz output I get is the one to be expected from manual_example.tsv not the one of the custom my_manual_example.tsv

I might have missed a step  ... 

Maybe the safest would be to explicitely specificy the input file when runnin conda run -n lotus_env MODE=manual make manual-entry  ?

**Comment by Adafede** [comment]
Just ran it with modifications and ran with modifications in the output.
So sadly could not reproduce...
@oolonek Could you try again and tell me if the error persists?

```
cd src
Rscript 1_gathering/db/manual/standardizing.R <path_to_your_file>
cd ..
make MODE=manual manual-entry
```

**Comment by Adafede** [comment]
actually commands changed now. @oolonek small check with the new ones?

**Comment by oolonek** [comment]
This issue is not of actuality anymore. 
Current problems are apparently due to new gnfinder / gnverifier output formats as discussed with @Adafede 
Closing this one for now.
